repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json

      - id: check-symlinks
      - id: destroyed-symlinks

      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: name-tests-test
        args: ["--pytest-test-first"]

      - id: check-merge-conflict
      - id: fix-byte-order-marker
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ["--fix=lf"]

      - id: detect-private-key
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]

  - repo: local
    hooks:
      - id: format
        name: format (ruff)
        entry: uv run ruff format
        language: system
        pass_filenames: false
        stages: [pre-commit, pre-push]
        types: [python]

      - id: lint
        name: lint (ruff)
        entry: uv run ruff check --fix
        language: system
        pass_filenames: false
        stages: [pre-commit, pre-push]
        types: [python]

      - id: type
        name: type (ty)
        entry: uv run ty check
        language: system
        pass_filenames: false
        stages: [pre-commit, pre-push]
        types: [python]

      - id: test
        name: test (pytest)
        entry: uv run pytest --cov
        language: system
        pass_filenames: false
        stages: [pre-commit, pre-push]
        types: [python]
