"""Sphinx configuration for alphafold3_input."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal

from docutils import nodes
from sphinx.config import Config
from sphinx.domains.python import (
    ObjectEntry,
    PyGroupedField,
    PyObject,
    PythonDomain,
)
from sphinx.ext.autosummary import INSTANCE_ATTR
from sphinx.ext.intersphinx import InventoryAdapter, missing_reference
from sphinx.ext.napoleon import GoogleDocstring
from sphinx.locale import _ as localize
from sphinx.util.nodes import make_refnode

from alphafold3_input.__about__ import (
    __author__,
    __description__,
    __documentation__,
    __issues__,
    __module_name__,
    __repository__,
    __version__,
)

if TYPE_CHECKING:
    from docutils.nodes import Node, TextElement
    from sphinx.addnodes import pending_xref
    from sphinx.application import Sphinx
    from sphinx.environment import BuildEnvironment
    from sphinx.util.inventory import _InventoryItem as InventoryItem

project: str = __description__.rstrip(".")
"""Set the project name displayed in the documentation."""

author: str = __author__
"""Define the project author(s)."""

copyright: str = f"2025–%Y, {__author__}"  # noqa: RUF001
"""Provide the copyright statement.

The ``%Y`` placeholder is replaced with the current year.
"""

version: str = ".".join(__version__.split(".")[:2])
"""Set the short (major.minor) project version."""

release: str = __version__
"""Set the full project version."""

language: str = "en"
"""Define the language used for autogenerated documentation text."""

extensions: list[str] = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.intersphinx",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]
"""Enabled Sphinx extensions."""

add_module_names: bool = False
"""Whether Python object names include their module path."""

python_display_short_literal_types: bool = True
"""Whether ``Literal`` types are rendered in compact form."""

python_trailing_comma_in_multi_line_signatures: bool = True
"""Whether multi-line signatures include trailing commas."""

python_use_unqualified_type_names: bool = False
"""Whether type names are rendered without module qualifiers."""

trim_doctest_flags: bool = True
"""Whether doctest flags are stripped from rendered examples."""


def python_return_field() -> None:
    """Allow typed return fields in the Python domain."""
    for index, field in enumerate(PyObject.doc_field_types):
        if field.name == "returnvalue":
            PyObject.doc_field_types[index] = PyGroupedField(
                field.name,
                label=field.label,
                names=field.names,
                rolename="class",
                can_collapse=True,
            )
            break


def python_yield_field() -> None:
    """Allow typed yield fields in the Python domain."""
    PyObject.doc_field_types.append(
        PyGroupedField(
            "yieldvalue",
            label=localize("Yields"),
            names=("yields", "yield"),
            rolename="class",
            can_collapse=True,
        ),
    )


autosummary_generate: bool | list[str] = True
"""Whether autosummary stubs are generated automatically."""

autosummary_generate_overwrite: bool = True
"""Whether autosummary stub files are overwritten when regenerated."""

autosummary_ignore_module_all: bool = True
"""Whether autosummary ignores module ``__all__`` declarations."""

autoclass_content: Literal["class", "both", "init"] = "class"
"""Which class docstring content Sphinx includes for ``autoclass``."""

autodoc_class_signature: Literal["mixed", "separated"] = "mixed"
"""How class signatures are rendered in autodoc output."""

autodoc_member_order: Literal["alphabetical", "groupwise", "bysource"] = (
    "bysource"
)
"""Ordering strategy for documented members."""

autodoc_docstring_signature: bool = True
"""Whether autodoc reads signatures from docstrings when needed."""

autodoc_inherit_docstrings: bool = True
"""Whether undocumented members inherit parent docstrings."""

autodoc_preserve_defaults: bool = True
"""Whether function defaults are rendered exactly as written."""

autodoc_typehints: Literal[
    "signature",
    "description",
    "none",
    "both",
] = "none"
"""Where autodoc renders type hints."""

autodoc_typehints_format: Literal["fully-qualified", "short"] = "short"
"""How autodoc formats rendered type hints."""


def autodoc_skip_pydantic(
    app: Sphinx,
    what: Literal[
        "module",
        "class",
        "exception",
        "function",
        "decorator",
        "method",
        "property",
        "attribute",
        "data",
        "type",
    ],
    name: str,
    obj: object,
    skip: bool,
    options: dict[str, str],
) -> bool | None:
    """Skip class-body fields represented by the ``INSTANCE_ATTR`` sentinel."""
    del app, skip, options

    if what == "class" and obj == INSTANCE_ATTR:
        return True

    if name == "model_config":
        return True

    return None


napoleon_google_docstring: bool = True
"""Whether Google-style docstrings are parsed."""

napoleon_numpy_docstring: bool = False
"""Whether NumPy-style docstrings are parsed."""

napoleon_include_private_with_doc: bool = False
"""Whether private documented members are included."""

napoleon_include_special_with_doc: bool = True
"""Whether special documented members are included."""

napoleon_use_admonition_for_examples: bool = True
"""Whether examples render as admonitions."""

napoleon_use_admonition_for_notes: bool = True
"""Whether notes render as admonitions."""

napoleon_use_admonition_for_references: bool = True
"""Whether references render as admonitions."""

napoleon_use_ivar: bool = False
"""Whether attributes are rendered using ``:ivar:`` fields."""

napoleon_use_param: bool = True
"""Whether parameters render as individual ``:param:`` fields."""

napoleon_use_rtype: bool = True
"""Whether return types render as ``:rtype:`` fields."""

napoleon_preprocess_types: bool = False
"""Whether type strings are preprocessed for Sphinx cross-referencing."""

napoleon_attr_annotations: bool = False
"""Whether attribute annotations are used as type fallbacks."""

napoleon_custom_sections: list[str | tuple[str, str]] | None = [
    "Exports",
]
"""Custom Napoleon sections supported by the project."""

napoleon_type_aliases: dict[str, str] | None = {
    "Sequence": "~collections.abc.Sequence",
    "Mapping": "~collections.abc.Mapping",
    "Iterable": "~collections.abc.Iterable",
    "Path": "~pathlib.Path",
    "Mol": "~rdkit.Chem.rdchem.Mol",
    "Any": "~typing.Any",
    "Self": "~typing.Self",
}
"""Type alias replacements used when parsing docstrings."""


def napoleon_fields_consumer(
    self: GoogleDocstring,
    *,
    parse_type: bool = True,
    prefer_type: bool = False,
    multiple: bool = False,
) -> list[tuple[str, str, list[str]]]:
    """Consume a Google-style fields section."""
    self._consume_empty()

    fields: list[tuple[str, str, list[str]]] = []

    while not self._is_section_break():
        name, typehint, description = self._consume_field(
            parse_type,
            prefer_type,
        )

        if not any((name, typehint, description)):
            continue

        if multiple and name:
            fields.extend(
                (item.strip(), typehint, description)
                for item in name.split(",")
            )
        else:
            fields.append((name, typehint, description))

    return fields


def napoleon_returns_consumer(
    self: GoogleDocstring,
    *,
    preprocess_types: bool = False,
) -> list[tuple[str, str, list[str]]]:
    """Consume a Google-style returns section."""
    del preprocess_types

    lines: list[str] = self._dedent(self._consume_to_next_section())
    config: Config = getattr(self, "_config", Config())

    if not lines:
        return []

    name: str = ""
    typehint: str = ""
    description: list[str] = lines[1:]

    prefix, colon, suffix = self._partition_field_on_colon(lines[0])

    if colon:
        typehint = prefix
        description: list[str] = [suffix, *description]

    description = self.__class__(description, config).lines()

    return [(name, typehint, description)]


def napoleon_attributes_parser(
    self: GoogleDocstring,
    section: str,
) -> list[str]:
    """Parse an ``Attributes`` section."""
    del section

    lines: list[str] = []
    config: Config = getattr(self, "_config", Config())

    for name, typehint, description in self._consume_fields():
        if config.napoleon_use_ivar:
            fields: list[str] = self._format_block(
                f":ivar {name}: ",
                description,
            )
            lines.extend(fields)
            if typehint:
                lines.append(f":vartype {name}: {typehint}")
        else:
            lines.append(f".. py:attribute:: {name}")
            if typehint:
                lines.append(f"   :type: {typehint}")
            if self._no_index:
                lines.append("   :no-index:")
            lines.append("")
            fields = self._format_field("", "", description)
            lines.extend(self._indent(fields, 3))
            lines.append("")

    if config.napoleon_use_ivar:
        lines.append("")

    return lines


def napoleon_methods_parser(
    self: GoogleDocstring,
    section: str,
) -> list[str]:
    """Parse an ``Methods`` section."""
    del section
    self._consume_fields(parse_type=False)

    return []


def napoleon_returns_parser(
    self: GoogleDocstring,
    section: str,
    directive: Literal["returns", "yields"],
) -> list[str]:
    """Parse a ``Returns`` or ``Yields`` sections."""
    del section

    lines: list[str] = []
    config: Config = getattr(self, "_config", Config())

    for _name, typehint, description in self._consume_returns_section():
        if config.napoleon_use_rtype and typehint:
            lines.extend(
                self._format_block(f":{directive} {typehint}: ", description),
            )
        else:
            lines.extend(self._format_block(f":{directive}: ", description))

    if lines and lines[-1]:
        lines.append("")

    return lines


intersphinx_mapping: dict[
    str,
    tuple[str, str | tuple[str | None, ...] | None],
] = {
    "python": ("https://docs.python.org/3", None),
    "pydantic": ("https://docs.pydantic.dev/latest/", None),
    "rdkit": ("https://www.rdkit.org/docs/", None),
}
"""External documentation inventories available for cross-references."""


def module_type_aliases(
    app: Sphinx,
    env: BuildEnvironment,
) -> None:
    """Build local package aliases for Python references."""
    del app

    domain: PythonDomain = env.domains["py"]
    objects: dict[str, ObjectEntry] = domain.objects

    aliases: dict[str, str] = {}

    for name, entry in objects.items():
        match name.split("."):
            case [module, _submodule, alias] if module == __module_name__:
                pass
            case _:
                continue

        if entry.objtype not in {"class", "exception"}:
            continue

        if alias in aliases and aliases[alias] != name:
            msg: str = (
                f"Conflicting alias '{alias}' for '{name}' and "
                f"'{aliases[alias]}' in intersphinx inventory."
            )
            raise ValueError(msg)

        aliases[alias] = name

    setattr(env, "module_type_aliases", aliases)


def resolve_builtins_reference(
    app: Sphinx,
    env: BuildEnvironment,
    node: pending_xref,
    contnode: TextElement,
) -> Node | None:
    """Resolve ``None``, ``True``, and ``False`` references."""
    del app, env

    if node.get("refdomain") != "py":
        return None

    target: Any = node.get("reftarget")
    if not isinstance(target, str) or target == "":
        return None

    if target in ("None", "True", "False"):
        return nodes.reference(
            "",
            "",
            contnode,
            internal=False,
            refuri=f"https://docs.python.org/3/library/constants.html#{target}",
        )

    return None


def resolve_self_reference(
    app: Sphinx,
    env: BuildEnvironment,
    node: pending_xref,
    contnode: TextElement,
) -> Node | None:
    """Resolve ``Self`` references against the current class context."""
    if node.get("refdomain") != "py":
        return None

    target: Any = node.get("reftarget")
    if not isinstance(target, str) or target == "":
        return None

    domain: PythonDomain = env.domains["py"]
    objects: dict[str, ObjectEntry] = domain.objects

    content: TextElement = contnode.deepcopy()

    if target == "Self":
        module: str | None = node.get("py:module")
        element: str | None = node.get("py:class")

        if module is None or element is None:
            return None

        candidate = f"{module}.{element}"

        if candidate in objects:
            for child in content.children:
                if isinstance(child, nodes.Text) and child == "Self":
                    child.parent.replace(child, nodes.Text(element))

            return make_refnode(
                app.builder,
                node.get("refdoc", env.docname),
                objects[candidate].docname,
                objects[candidate].node_id,
                [content],
                candidate,
            )

    return None


def resolve_local_reference(
    app: Sphinx,
    env: BuildEnvironment,
    node: pending_xref,
    contnode: TextElement,
) -> Node | None:
    """Resolve local package references using cached aliases."""
    if node.get("refdomain") != "py":
        return None

    target: Any = node.get("reftarget")
    if not isinstance(target, str) or target == "":
        return None

    domain: PythonDomain = env.domains["py"]
    objects: dict[str, ObjectEntry] = domain.objects

    if aliases := getattr(env, "module_type_aliases", None):
        for alias, candidate in aliases.items():
            if alias in target and candidate in objects:
                return domain.resolve_xref(
                    env=env,
                    fromdocname=node.get("refdoc", env.docname),
                    builder=app.builder,
                    type=node["reftype"],
                    target=target.replace(alias, candidate),
                    node=node,
                    contnode=contnode,
                )

    return None


def resolve_global_reference(  # noqa: C901
    app: Sphinx,
    env: BuildEnvironment,
    node: pending_xref,
    contnode: TextElement,
) -> Node | None:
    """Resolve configured global aliases via intersphinx.

    If the fully qualified target cannot be resolved directly, fall back to the
    longest documented Python-object prefix and synthesize a URL by replacing
    the fragment with the full candidate target.
    """
    if node.get("refdomain") != "py":
        return None

    target: Any = node.get("reftarget")
    if not isinstance(target, str) or target == "":
        return None

    config: Config = getattr(env, "config", Config())
    reference: pending_xref = node.deepcopy()
    content: TextElement = contnode.deepcopy()

    candidate: str | None = None
    if aliases := getattr(config, "napoleon_type_aliases", None):
        for alias, _candidate in aliases.items():
            if alias in target:
                candidate: str | None = _candidate.lstrip("~")
                break

    if not candidate:
        return None

    reference["reftarget"] = target.replace(alias, candidate)

    if resolved := missing_reference(app, env, reference, content):
        return resolved

    inventories = InventoryAdapter(env)

    while candidate:
        candidate, _, _ = candidate.rpartition(".")

        for role in inventories.main_inventory.values():
            item: InventoryItem | None = role.get(candidate)

            if item is not None:
                base, _, _ = item.uri.partition("#")
                return nodes.reference(
                    "",
                    "",
                    content,
                    internal=False,
                    refuri=f"{base}#{reference['reftarget']}",
                )

    return None


html_theme: str = "furo"
"""HTML theme used for built documentation."""

html_theme_options: dict[str, str | list[str]] = {
    "source_repository": __repository__,
    "source_branch": "main",
    "source_directory": "docs/",
    "top_of_page_buttons": [],
}
"""Theme-specific HTML configuration."""

html_title: str = f"{project} (v{release})"
"""Title displayed in the browser and page metadata."""

html_permalinks: bool = True
"""Whether section headings receive permalink anchors."""

html_permalinks_icon: str = "#"
"""Icon used for heading permalinks."""

rst_epilog = f"""
.. |docs-url| replace:: {__documentation__}
.. |issues-url| replace:: {__issues__}
.. |repo-url| replace:: {__repository__}
.. |project-summary| replace:: {__description__}
"""
"""Shared reStructuredText substitutions appended to every source file."""


def setup(app: Sphinx) -> None:
    """Register custom Sphinx hooks and Napoleon patches."""
    python_return_field()
    python_yield_field()

    setattr(
        GoogleDocstring,
        "_consume_fields",
        napoleon_fields_consumer,
    )
    setattr(
        GoogleDocstring,
        "_consume_returns_section",
        napoleon_returns_consumer,
    )

    setattr(
        GoogleDocstring,
        "_parse_attributes_section",
        napoleon_attributes_parser,
    )
    setattr(
        GoogleDocstring,
        "_parse_methods_section",
        napoleon_methods_parser,
    )
    setattr(
        GoogleDocstring,
        "_parse_yields_section",
        lambda self, section: napoleon_returns_parser(
            self,
            section=section,
            directive="yields",
        ),
    )
    setattr(
        GoogleDocstring,
        "_parse_returns_section",
        lambda self, section: napoleon_returns_parser(
            self,
            section=section,
            directive="returns",
        ),
    )

    app.connect(
        event="autodoc-skip-member",
        callback=autodoc_skip_pydantic,
        priority=500,
    )
    app.connect(
        "env-updated",
        module_type_aliases,
        priority=500,
    )

    app.connect(
        "missing-reference",
        resolve_builtins_reference,
        priority=500,
    )
    app.connect(
        "missing-reference",
        resolve_self_reference,
        priority=500,
    )
    app.connect(
        "missing-reference",
        resolve_local_reference,
        priority=500,
    )
    app.connect(
        "missing-reference",
        resolve_global_reference,
        priority=500,
    )
