"""Sphinx configuration for alphafold3_input."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal

from sphinx.config import Config
from sphinx.domains.python import PyGroupedField, PyObject
from sphinx.ext.autosummary import INSTANCE_ATTR
from sphinx.ext.napoleon import GoogleDocstring
from sphinx.locale import _

from alphafold3_input.__about__ import (
    __author__,
    __description__,
    __repository__,
    __version__,
)

if TYPE_CHECKING:
    from sphinx.application import Sphinx


# GENERAL CONFIGURATION

project: str = __description__.rstrip(".")
"""Set the project name displayed in the documentation."""

author: str = __author__
"""Define the project author(s)."""

copyright: str = f"2025–%Y, {__author__}"  # noqa: RUF001
"""Provide the copyright statement.

The ``%Y`` placeholder is replaced with the current year.
"""

version: str = ".".join(__version__.split(".")[:2])
"""Set the short (major.minor) project version."""

release: str = __version__
"""Set the full project version."""

language: str = "en"
"""Define the language used for autogenerated documentation text."""

extensions: list[str] = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.intersphinx",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]
"""Enable Sphinx extensions used for documentation generation."""


# PYTHON DOMAIN CONFIGURATION

add_module_names: bool = False
"""Prepend module names to Python domain object names.

Controls whether objects such as functions or classes are displayed with
their module prefix.
"""

modindex_common_prefix: list[str] = []
"""Ignore prefixes when sorting the Python module index.

Entries in this list are stripped when grouping modules in the index,
e.g. ``["foo."]`` places ``foo.bar`` under ``B`` instead of ``F``.
"""

python_display_short_literal_types: bool = True
"""Render ``Literal`` types using a compact union-style syntax.

When enabled, ``Literal["a", "b"]`` is displayed as ``"a" | "b"``.
"""

python_maximum_signature_line_length: int | None = None
"""Wrap Python signatures exceeding a given length.

If set, parameters are split across multiple lines when the signature
length exceeds this value. ``None`` disables wrapping.
"""

python_trailing_comma_in_multi_line_signatures: bool = True
"""Include trailing commas in multi-line Python signatures."""

python_use_unqualified_type_names: bool = False
"""Omit module prefixes in resolved type references.

When enabled, types are displayed without their fully qualified module
path if they can be resolved.
"""

trim_doctest_flags: bool = True
"""Remove doctest flags and markers from interactive code blocks.

Strips comments like ``# doctest: ...`` and ``<BLANKLINE>`` markers from
rendered doctests.
"""


def python_return_field() -> None:
    """Allow typed return fields in the Python domain.

    Replaces the default return-value field with a grouped field so that
    typed ``:return:`` and ``:returns:`` fields are parsed inline.
    """
    for index, field in enumerate(PyObject.doc_field_types):
        if field.name == "returnvalue":
            PyObject.doc_field_types[index] = PyGroupedField(
                field.name,
                label=field.label,
                names=field.names,
                rolename="class",
                can_collapse=True,
            )
            break


def python_yield_field() -> None:
    """Allow typed yield fields in the Python domain.

    Adds a new grouped field for typed ``:yield:`` and `:yields:`` directives.
    """
    PyObject.doc_field_types.append(
        PyGroupedField(
            "yieldvalue",
            label=_("Yields"),
            names=("yields", "yield"),
            rolename="class",
            can_collapse=True,
        ),
    )


# AUTOSUMMARY CONFIGURATION

autosummary_context: dict[str, object] = {}
"""Provide additional template context for generated autosummary stubs.

Values in this mapping are exposed to the template engine when rendering
autosummary stub pages.
"""

autosummary_generate: bool | list[str] = True
"""Generate stub pages for discovered ``autosummary`` directives.

Set this to ``True`` to scan all found documents, or to a list of document
names to limit stub generation to specific files.
"""

autosummary_generate_overwrite: bool = True
"""Overwrite existing autosummary stub files when regenerating them."""

autosummary_mock_imports: list[str] = []
"""Mock unavailable imports during autosummary generation.

This behaves like ``autodoc_mock_imports`` and is useful when optional
dependencies are not installed at build time.
"""

autosummary_imported_members: bool = False
"""Include imported classes and functions in autosummary output.

When disabled, autosummary documents only members defined directly in the
target module, except where ``__all__`` handling overrides this behavior.
"""

autosummary_ignore_module_all: bool = True
"""Ignore ``__all__`` when selecting members for autosummary.

When set to ``False``, autosummary documents exactly the names listed in
``__all__`` and excludes other module members.
"""

autosummary_filename_map: dict[str, str] = {}
"""Map object names to explicit stub filenames.

Use this to avoid filename collisions on case-insensitive file systems or
whenever multiple object names would otherwise resolve to the same path.
"""


# AUTODOC CONFIGURATION

autodoc_use_legacy_class_based: bool = False
"""Use the legacy class-based autodoc implementation for compatibility.

Enable this only if your documentation or an extension depends on the
pre-Sphinx-9 class-based autodoc API.
"""

autoclass_content: Literal[
    "class",
    "both",
    "init",
] = "class"
"""Select which docstring content an ``autoclass`` directive inserts.

``"class"`` uses only the class docstring, ``"init"`` uses only the
``__init__`` docstring, and ``"both"`` concatenates both.
"""

autodoc_class_signature: Literal[
    "mixed",
    "separated",
] = "mixed"
"""Control how class signatures are rendered by ``autoclass``.

``"mixed"`` shows the signature with the class name, while
``"separated"`` renders the signature as a separate method-like line.
"""

autodoc_member_order: Literal[
    "alphabetical",
    "groupwise",
    "bysource",
] = "bysource"
"""Define the order of members in ``automodule`` and ``autoclass`` output.

``"alphabetical"`` sorts by name, ``"groupwise"`` groups by member type,
and ``"bysource"`` preserves source order when source code is available.
"""

autodoc_default_options: dict[str, str | bool] = {}
"""Apply default options to all autodoc directives.

This can be used to enable common options globally, such as ``members``,
``undoc-members``, ``member-order``, or ``exclude-members``.
"""

autodoc_docstring_signature: bool = True
"""Use signature lines at the top of docstrings when introspection fails.

This is mainly useful for C extensions or overloaded callables whose
signatures are written explicitly in the docstring.
"""

autodoc_mock_imports: list[str] = []
"""Mock top-level imports that are unavailable at build time.

Only root package names should be listed; all submodules below them are
mocked automatically.
"""

autodoc_typehints: Literal[
    "signature",
    "description",
    "none",
    "both",
] = "none"
"""Control where autodoc renders type hints.

Use ``"signature"`` to show them in signatures, ``"description"`` to move
them into the body, ``"both"`` to show both, and ``"none"`` to suppress
them entirely.
"""

autodoc_typehints_description_target: Literal[
    "all",
    "documented",
    "documented_params",
] = "all"
"""Control which documented items receive type hints in descriptions.

This setting applies when ``autodoc_typehints`` is set to ``"description"``.
"""

autodoc_type_aliases: dict[str, str] = {}
"""Map user-defined type aliases to fully qualified object names.

This preserves aliases in rendered documentation instead of expanding them
into their full underlying types.
"""

autodoc_typehints_format: Literal[
    "fully-qualified",
    "short",
] = "short"
"""Control whether rendered type hints include full module paths.

``"fully-qualified"`` keeps module prefixes, while ``"short"`` suppresses
them where possible.
"""

autodoc_preserve_defaults: bool = True
"""Preserve default argument values exactly as written in source code."""

autodoc_use_type_comments: bool = True
"""Read ``# type: ...`` comments to supplement missing annotations.

Disable this if the codebase uses only inline annotations or does not use
type comments at all.
"""

autodoc_warningiserror: bool = True
"""Control autodoc behavior under ``--fail-on-warning`` during imports.

This setting is retained for compatibility, though it has no practical
effect in newer Sphinx versions where warnings no longer abort early.
"""

autodoc_inherit_docstrings: bool = True
"""Inherit missing class and method docstrings from parent objects.

When enabled, undocumented subclasses and overridden methods reuse
docstrings from their bases where appropriate.
"""

suppress_warnings: tuple[str, ...] = ()
"""Suppress selected Sphinx warning categories.

For autodoc, useful categories include ``"autodoc"`` and
``"autodoc.import_object"``.
"""


def autodoc_skip_pydantic(
    app: Sphinx,
    what: Literal[
        "module",
        "class",
        "exception",
        "function",
        "decorator",
        "method",
        "property",
        "attribute",
        "data",
        "type",
    ],
    name: str,
    obj: object,
    skip: bool,
    options: dict[str, str],
) -> bool | None:
    """Skip class-body fields represented by the ``INSTANCE_ATTR`` sentinel.

    Sphinx uses ``INSTANCE_ATTR`` for documented instance attributes (such as
    Pydantic model fields) that do not exist as ordinary runtime objects. This
    hook filters out such members when they are encountered under a class.

    Args:
        app (Sphinx): Sphinx application instance.
        what (Literal["module", "class", "exception", "function",
            "decorator", "method", "property", "attribute", "data",
            "type"]): Type of the parent object being documented.
        name (str): Member name passed by autodoc.
        obj (object): Member object or autodoc sentinel.
        skip (bool): Default autodoc skip decision.
        options (dict[str, str]): Autodoc directive options.

    Returns:
        bool | None: ``True`` if the member should be skipped, otherwise
        ``None`` to keep autodoc's default behavior.
    """
    del app, name, skip, options

    if what == "class" and obj == INSTANCE_ATTR:
        return True

    return None


# NAPOLEON CONFIGURATION

napoleon_google_docstring: bool = True
"""Parse Google-style docstrings.

Disable this only if the codebase does not use Google-style sections such as
``Args:``, ``Returns:``, or ``Raises:``.
"""

napoleon_numpy_docstring: bool = False
"""Parse NumPy-style docstrings.

Disable this if the project uses only Google-style docstrings and NumPy-style
section parsing is not needed.
"""

napoleon_include_init_with_doc: bool = False
"""Document ``__init__`` docstrings separately when they are present.

When disabled, Sphinx falls back to its default behavior for constructor
docstrings instead of listing them as separate documented members.
"""

napoleon_include_private_with_doc: bool = False
"""Include private members with docstrings in generated documentation.

Private members are names like ``_member``. When disabled, they follow
Sphinx's default private-member handling.
"""

napoleon_include_special_with_doc: bool = True
"""Include special members with docstrings in generated documentation.

Special members are names like ``__str__`` or ``__call__``.
"""

napoleon_use_admonition_for_examples: bool = True
"""Render ``Example`` and ``Examples`` sections as admonitions.

When disabled, these sections are rendered using a rubric instead.
"""

napoleon_use_admonition_for_notes: bool = True
"""Render ``Notes`` sections as admonitions.

When disabled, ``Notes`` is rendered using a rubric. The singular
``Note`` section is always rendered as a note directive.
"""

napoleon_use_admonition_for_references: bool = True
"""Render ``References`` sections as admonitions.

When disabled, these sections are rendered using a rubric instead.
"""

napoleon_use_ivar: bool = False
"""Render documented attributes using ``:ivar:`` fields.

When disabled, Napoleon emits ``.. attribute::`` directives instead.
"""

napoleon_use_param: bool = True
"""Render each parameter as a separate ``:param:`` field.

When disabled, parameters are grouped into a single combined parameters block.
"""

napoleon_use_keyword: bool = False
"""Render each keyword argument as a separate ``:keyword:`` field.

When disabled, keyword arguments are grouped into a single combined section.
"""

napoleon_use_rtype: bool = True
"""Render return types using a separate ``:rtype:`` field.

When disabled, return types are rendered inline with the return description.
"""

napoleon_preprocess_types: bool = False
"""Preprocess type names in docstrings into references where possible.

This allows docstring type expressions to be rewritten using configured
aliases and cross-references.
"""

napoleon_type_aliases: dict[str, str] | None = {
    "Sequence": "~collections.abc.Sequence",
    "Mapping": "~collections.abc.Mapping",
    "Iterable": "~collections.abc.Iterable",
    "Path": "~pathlib.Path",
    "Mol": "~rdkit.Chem.rdchem.Mol",
    "Any": "~typing.Any",
    "Self": "~typing.Self",
}
"""Map docstring type names to replacement references or canonical names.

This is useful for translating short or informal type names into
fully-qualified references or glossary terms.
"""

napoleon_attr_annotations: bool = False
"""Use class body annotations to infer attribute types when needed.

If an attribute is documented in a docstring without an explicit type,
its annotation from the class body is used instead.
"""

napoleon_custom_sections: list[str | tuple[str, str]] | None = [
    "Exports",
]
"""Register additional parsed docstring sections.

Entries may define generic sections, aliases for existing section types,
or custom sections rendered like parameter or return blocks.
"""


def napoleon_type_resolve(
    self: GoogleDocstring,
    typehint: str,
) -> str:
    """Resolve a Napoleon type hint.

    Rewrites ``Self`` to the owning class name and expands configured
    Napoleon type aliases.

    Args:
        typehint (str): Raw type hint extracted from a docstring section.

    Returns:
        str: Resolved type hint string.
    """
    resolved: str = typehint

    config: Config = getattr(self, "_config", Config())
    element: Any = getattr(self, "_obj", None)

    if "Self" in resolved and element is not None:
        if isinstance(element, type):
            resolved = resolved.replace("Self", element.__name__)
        else:
            resolved = resolved.replace(
                "Self",
                element.__qualname__.rsplit(".", 1)[0],
            )

    if aliases := config.napoleon_type_aliases:
        for alias, reference in aliases.items():
            if alias in resolved:
                resolved: str = resolved.replace(alias, reference)

    return resolved


def napoleon_fields_consumer(
    self: GoogleDocstring,
    parse_type: bool = True,
    prefer_type: bool = False,
    multiple: bool = False,
) -> list[tuple[str, str, list[str]]]:
    """Consume a field-style Napoleon section.

    This wraps the default field consumer and applies shared type-hint
    resolution to each parsed field.

    Args:
        parse_type (bool): Whether to parse an inline type from the field
            header.
        prefer_type (bool): Whether to treat an untyped field name as a type.
        multiple (bool): Whether comma-separated field names should be split
            into multiple entries.

    Returns:
        list[tuple[str, str, list[str]]]: Parsed field entries as
        ``(name, typehint, description)`` tuples.
    """
    self._consume_empty()

    fields: list[tuple[str, str, list[str]]] = []

    while not self._is_section_break():
        name, typehint, description = self._consume_field(
            parse_type,
            prefer_type,
        )

        if not any((name, typehint, description)):
            continue

        typehint: str = napoleon_type_resolve(self, typehint)

        if multiple and name:
            fields.extend(
                (item.strip(), typehint, description)
                for item in name.split(",")
            )
        else:
            fields.append((name, typehint, description))

    return fields


def napoleon_return_consumer(
    self: GoogleDocstring,
    preprocess_types: bool = False,
) -> list[tuple[str, str, list[str]]]:
    """Consume a Google-style ``Returns`` section.

    Parses the section into a single return entry and applies shared
    type-hint resolution to the parsed return type.

    Args:
        preprocess_types (bool): Unused compatibility parameter retained to
            match Napoleon's original method signature.

    Returns:
        list[tuple[str, str, list[str]]]: Parsed return entries as
        ``(name, typehint, description)`` tuples.
    """
    del preprocess_types

    lines: list[str] = self._dedent(self._consume_to_next_section())
    config: Config = getattr(self, "_config", Config())

    if not lines:
        return []

    name: str = ""
    typehint: str = ""
    description: list[str] = lines[1:]

    prefix, colon, suffix = self._partition_field_on_colon(lines[0])

    if colon:
        typehint: str = prefix
        description: list[str] = [suffix, *description]

    typehint: str = napoleon_type_resolve(self, typehint)
    description: list[str] = self.__class__(description, config).lines()

    return [(name, typehint, description)]


def napoleon_attributes_parser(
    self: GoogleDocstring,
    section: str,
) -> list[str]:
    """Parse an ``Attributes`` section.

    Follows the default Google-style attribute parser, while preserving
    ``ivar`` behavior and rendering attribute types through the shared
    type-resolution path.

    Args:
        section (str): Section label currently being parsed.

    Returns:
        list[str]: Lines of reStructuredText representing the parsed
        attributes.
    """
    del section

    lines: list[str] = []
    config: Config = getattr(self, "_config", Config())

    for name, typehint, description in self._consume_fields():
        resolved: str = typehint or napoleon_type_resolve(
            self,
            self._lookup_annotation(name),
        )

        if config.napoleon_use_ivar:
            fields: list[str] = self._format_block(
                f":ivar {name}: ",
                description,
            )
            lines.extend(fields)
            if resolved:
                lines.append(f":vartype {name}: {resolved}")
        else:
            lines.append(f".. py:attribute:: {name}")
            if resolved:
                lines.append(f"   :type: {resolved}")
            if self._no_index:
                lines.append("   :no-index:")
            lines.append("")

            fields = self._format_field("", "", description)
            lines.extend(self._indent(fields, 3))
            lines.append("")

    if config.napoleon_use_ivar:
        lines.append("")

    return lines


def napoleon_return_parser(
    self: GoogleDocstring,
    section: str,
) -> list[str]:
    """Parse a ``Returns`` section.

    Follows the default Google-style return parser, but renders resolved
    return types inline using typed ``:returns:`` fields.

    Args:
        section (str): Section label currently being parsed.

    Returns:
        list[str]: Lines of reStructuredText representing the parsed
        returns.
    """
    del section

    lines: list[str] = []
    config: Config = getattr(self, "_config", Config())

    for _name, typehint, description in self._consume_returns_section():
        if config.napoleon_use_rtype and typehint:
            lines.extend(
                self._format_block(
                    f":returns {typehint}: ",
                    description,
                ),
            )
        else:
            lines.extend(
                self._format_block(
                    ":returns: ",
                    description,
                ),
            )

    if lines and lines[-1]:
        lines.append("")

    return lines


def napoleon_yields_parser(
    self: GoogleDocstring,
    section: str,
) -> list[str]:
    """Parse a ``Yields`` section.

    Reuses the return parser but emits ``:yields:`` instead of ``:returns:``.
    """
    del section

    lines: list[str] = []
    config: Config = getattr(self, "_config", Config())

    for _name, typehint, description in self._consume_returns_section():
        if config.napoleon_use_rtype and typehint:
            lines.extend(
                self._format_block(
                    f":yields {typehint}: ",
                    description,
                ),
            )
        else:
            lines.extend(
                self._format_block(
                    ":yields: ",
                    description,
                ),
            )

    if lines and lines[-1]:
        lines.append("")

    return lines


# INTERSPHINX CONFIGURATION

intersphinx_mapping: dict[
    str,
    tuple[str, str | tuple[str | None, ...] | None],
] = {
    "python": ("https://docs.python.org/3", None),
    "pydantic": ("https://docs.pydantic.dev/latest/", None),
    "rdkit": ("https://www.rdkit.org/docs/", None),
}
"""Map external documentation sets to their base URLs and inventories.

Each entry links a unique key to a target documentation root and an
optional inventory location.
"""

intersphinx_resolve_self: str = ""
"""Resolve references to this project as local instead of external.

Use this when documentation is shared across projects but should resolve
references to the current project locally.
"""

intersphinx_cache_limit: int = 5
"""Cache remote inventories for a given number of days.

Use a negative value to cache inventories indefinitely.
"""

intersphinx_timeout: int | float | None = None
"""Set the response timeout for fetching remote inventories.

``None`` disables the timeout.
"""

intersphinx_disabled_reftypes: list[str] = ["std:doc"]
"""Disable selected reference types for implicit intersphinx resolution.

Entries may target a specific role, a whole domain via ``domain:*``, or
all cross-references via ``*``.
"""


# HTML BUILDER CONFIGURATION

html_theme: str = "furo"
"""Select the HTML theme used for documentation output."""

html_theme_options: dict[str, str | list[str]] = {
    "source_repository": __repository__,
    "source_branch": "main",
    "source_directory": "docs/source/",
    "top_of_page_buttons": [],
}
"""Configure theme-specific appearance options.

The available options depend on the selected theme.
"""

html_title: str = f"{project} (v{release})"
"""Set the document title displayed in the browser and navigation."""

html_permalinks: bool = True
"""Add anchor links to headings and description blocks."""

html_permalinks_icon: str = "#"
"""Set the symbol used for heading anchor links."""


# SPHINX HOOKS


def setup(app: Sphinx) -> None:
    """Register custom Sphinx hooks and Napoleon patches.

    Args:
        app (Sphinx): Sphinx application instance.
    """
    python_return_field()
    python_yield_field()
    setattr(
        GoogleDocstring,
        "_consume_fields",
        napoleon_fields_consumer,
    )
    setattr(
        GoogleDocstring,
        "_parse_attributes_section",
        napoleon_attributes_parser,
    )
    setattr(
        GoogleDocstring,
        "_consume_returns_section",
        napoleon_return_consumer,
    )
    setattr(
        GoogleDocstring,
        "_parse_yields_section",
        napoleon_yields_parser,
    )
    setattr(
        GoogleDocstring,
        "_parse_returns_section",
        napoleon_return_parser,
    )
    app.connect(
        event="autodoc-skip-member",
        callback=autodoc_skip_pydantic,
        priority=500,
    )
